AWSTemplateFormatVersion: '2010-09-09'
Description: Provision a simple Amazon Linux Instance and allow SSH connectivity.
Parameters:
  KeyPairName:
    Description: EC2 Key Pair for SSH Access, you must have created these prior to
      running this.
    Type: AWS::EC2::KeyPair::KeyName
    Default: batch11_keypair
  TheCloudNationVpcId:
    Description: 'VPC for creating instance using CFT'
    # Type: AWS::EC2::VPC::Id
    Type: String
    Default: vpc-0b2075324eb857dc6

  TheCloudNationAmiId:
    Description: 'Using Amazon Linux Image for creating this Instance'
    Type: String
    Default: ami-03b644b4d078605bd

  TheCloudNationInstanceType:
    Description: 'Instance type configuration'
    Type: String
    Default: t3.micro

  TheCloudNationSubnetId:
    Description: 'Giving the public-subnet1 for this instance'
    # Type: AWS::EC2::Subnet::Id
    Type: String
    Default: subnet-0b9da844dd4ec1329    

Resources:
  TheCloudNationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Batch11 Security Group for test purpose
      GroupName: TheCloudNationSecurityGroup
      SecurityGroupIngress: 
        # - IpProtocol: tcp
        #   FromPort: 22
        #   ToPort: 22
        #   CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 49.37.133.176/32       
      Tags: 
        - Key: "Name"
          Value: "TheCloudNationSecurityGroup"
      VpcId: !Ref TheCloudNationVpcId

  TheCloudNationInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPairName
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !Ref TheCloudNationSecurityGroup
      Tags:
        - Key: "Name"
          Value: "TheCloudNation Instance"    

  TheCloudNationEIP:
    Type: AWS::EC2::EIP
    Properties: 
      Tags: 
        - Key: "Name"
          Value: "TheCloudNation EIP"  

  TheCloudNationEipAssociate:
    Type: AWS::EC2::EIPAssociation
    Properties: 
        EIP: !Ref TheCloudNationEIP
        InstanceId: !Ref TheCloudNationInstance
